apiVersion: v1
kind: Service
metadata:
  name: {{ include "gel-server.fullname" . }}
  labels:
    {{- include "gel-server.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml .  | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gel
      protocol: TCP
      name: gel
  selector:
    {{- include "gel-server.selectorLabels" . | nindent 4 }}
