# Default values for gel-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: "geldata/gel"
  pullPolicy: IfNotPresent
  tag: "7.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: "100%"
    maxUnavailable: 0

labels: {}

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

config:
  logLevel: "info"          # options: "debug", "info", "warn", "error", "silent" ref: https://docs.geldata.com/reference/running/configuration#gel-server-log-level
  security:
    tls: {}
      # existingSecret: "gel-tls-cert"  # name of secret containing tls.crt / tls.key

extraEnv: {}
  # Full list of environment variables: https://docs.geldata.com/reference/running/configuration
  # GEL_DOCKER_LOG_LEVEL: "info"

# extraEnvFromSecrets:
#   - name: gel-db-creds
#   - name: gel-server-password

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /server/status/alive
    port: http
readinessProbe:
  httpGet:
    path: /server/status/ready
    port: http

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false
  automount: true
  labels: {}
  annotations: {}
  name: ""
  imagePullSecrets: []

service:
  type: ClusterIP
  port: 5656
  labels: {}
  annotations: {}

persistence:
  enabled: true

  # When empty, default StorageClass is used
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # If you want to use an existing PVC
  existingClaim: ""
  labels: {}
  annotations: {}
